# dist: trusty
sudo: required
language: generic

services:
  - docker

before_install:
  - sudo apt-get -q update
  - sudo apt-get install -y texlive-latex-extra texlive-math-extra
  - docker pull jlimperg/agda-stdlib

script:
  - make docs

deploy:
  provider: pages
  local_dir: ./docs
  project_name: "Agda formalization of Intuitionistic Propositional Logic"
  skip_cleanup: true
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
