name: agda-setup

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # GitHub turns of scheduled runs after two months
  # schedule:
  #   # Run always at YYYY-MM-03 03:03am
  #   - cron: '3 3 3 * *'
  workflow_dispatch:

jobs:
  agda-build:
    name: Agda ${{ matrix.agda }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-latest
          agda: 2.6.2.2
        - os: macos-latest
          agda: 2.6.3
        - os: ubuntu-latest
          agda: 2.6.4.3
        - os: ubuntu-latest
          agda: 2.7.0.1

    steps:

      # Checkout to $HOME empties $HOME so we have to do it before we put stuff there.
      - uses: actions/checkout@v4

      - name: Setup Agda
        uses: wenkokke/setup-agda@main
        id:   setup
        with:
          agda-version: ${{ matrix.agda }}
          agda-stdlib-version: recommended
          # agda-stdlib-version: '1.7.1'
          # agda-stdlib-default: true

      - name: Cache build
        uses: actions/cache@v4
        id:   cache
        with:
          key: agda-setup-ci-agda-${{ steps.setup.outputs.agda-version }}
          # Don't have version of standard library. :-(
          # -std-lib-${{ matrix.std-lib }}
          path: |
            src/_build
            ~/.agda/libraries.d
# C:\Users\runneradmin\AppData\Roaming\agda\libraries.d\standard-library\v1.7.1

      - name: Run Agda
        working-directory: src
        run: agda Everything.agda --html
