name: wen-kokke-build

on:
  push:
    branches:
      - master
      - ci-*

jobs:
  agda-build:
    name: Agda-2.6.2.2 and std-lib
    runs-on: ubuntu-latest

    steps:

      # Checkout deletes stuff so we have to do it first.
      - uses: actions/checkout@v3

      - id:   cache
        uses: actions/cache@v3
        with:
          path: |
            agda-stdlib-1.7.1
            src/_build
          key: std-lib-1.7.1

      - name: After cache
        run: |
          pwd
          ls -al ~
          ls -al

      - name: Setup Agda
        uses: wenkokke/setup-agda@latest
        with:
          agda-version: '2.6.2.2'

      # Install standard library
      - name: Install agda-stdlib
        if:  ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          wget https://github.com/agda/agda-stdlib/archive/refs/tags/v1.7.1.zip
          unzip v1.7.1.zip

      - name: Before Agda
        run: |
          pwd
          ls -al

      - name: Run Agda
        run: agda -i agda-stdlib-1.7.1/src -i src src/Everything.agda --html
